Traceback (most recent call last):
  File "main.py", line 31, in <module>
    trainer = get_obj_from_str(configs.trainer.target)(configs)
  File "/data/FFHQ/DifFace_Thesis/trainer.py", line 58, in __init__
    self.init_logger()
  File "/data/FFHQ/DifFace_Thesis/trainer.py", line 115, in init_logger
    assert self.configs.resume
AssertionError
Traceback (most recent call last):
  File "main.py", line 31, in <module>
    trainer = get_obj_from_str(configs.trainer.target)(configs)
  File "/data/FFHQ/DifFace_Thesis/trainer.py", line 58, in __init__
    self.init_logger()
  File "/data/FFHQ/DifFace_Thesis/trainer.py", line 115, in init_logger
    assert self.configs.resume
AssertionError
